package com.codelens.common.agent;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class AnalysisTaskTest {

    @Test
    public void testCreateTask_WithInputAndType() {
        AnalysisTask<String, String> task = new AnalysisTask<>(TaskType.SUMMARY, "source code");

        assertEquals(TaskType.SUMMARY, task.getTaskType());
        assertEquals("source code", task.getInput());
        assertEquals(ExecutionStatus.PENDING, task.getStatus());
        assertNull(task.getOutput());
        assertNull(task.getCompletedAt());
        assertTrue(task.getCreatedAt() > 0);
    }

    @Test
    public void testSetOutput_UpdatesStatusAndCompletedAt() {
        AnalysisTask<String, String> task = new AnalysisTask<>(TaskType.SUMMARY, "input");
        assertNull(task.getCompletedAt());

        task.setOutput("result");

        assertEquals("result", task.getOutput());
        assertEquals(ExecutionStatus.COMPLETED, task.getStatus());
        assertNotNull(task.getCompletedAt());
        assertTrue(task.getCompletedAt() > 0);
    }

    @Test
    public void testTaskId_AutoGenerated() {
        AnalysisTask<String, String> task1 = new AnalysisTask<>(TaskType.SUMMARY, "a");
        AnalysisTask<String, String> task2 = new AnalysisTask<>(TaskType.SUMMARY, "a");

        assertNotNull(task1.getTaskId());
        assertFalse(task1.getTaskId().isEmpty());
        assertNotEquals(task1.getTaskId(), task2.getTaskId(), "每次创建应生成唯一 ID");
    }
}
